language: csharp
before_install:
  - nuget restore Newtonsoft.Json
install:
  - 
script:
  - xbuild /p:Configuration=Release qingstor-sdk-net35.sln
  - xbuild /p:Configuration=Release qingstor-sdk-net40.sln
  - xbuild /p:Configuration=Release qingstor-sdk-net45.sln